#
server:
  port: 8080
#
logging:
  config: classpath:logback-spring.xml
#
spring:
  application:
    name: study-dubbo-springboot
  main:
    web-application-type: none
  profiles:
    active: dubbo, @env@
