########## Config Start ##########
server:
  address: 127.0.0.1
  port: 9090
spring:
  application:
    name: spring-boot
dubbo:
  application:
    name:
  reg

logging:
  config: classpath:logback.xml
########## Config End ##########
