########## 基本配置 ##########
server:
  address: 127.0.0.1
  port: 8080
spring:
  application:
    name: spring-boot
########## Dubbo 配置 ##########
dubbo:
  application:
    name: study-dubbo-springboot-provider
  registry:
    address: zookeeper://116.196.74.61:2181
    timeout: 5000
    check: false
  protocols:
    dubbo:
      name: dubbo
      port: 20880
    http:
      name: http
      port: 8080
      server: tomcat
  provider:
    timeout: 5000
    retries: 0
    dispatcher: message
  scan:
    base-packages: study.dubbo.springboot.service
########## Log 配置 ##########
logging:
  config: classpath:logback.xml

