########## 基本配置 ##########
server:
  address: 127.0.0.1
  port: 8080
spring:
  application:
    name: study-dubbo-springboot
  main:
    web-application-type: none
########## Dubbo配置 ##########
dubbo:
  application:
    name: study-dubbo-springboot-provider
  registry:
    address: zookeeper://116.196.74.61:2181
    timeout: 5000
    check: false
  protocols:
    dubbo:
      name: dubbo
      port: 20880
    rest:
      name: rest
      port: 8080
      server: tomcat
  provider:
    timeout: 5000
    retries: 0
    dispatcher: message
    version: 1.0.0
  scan:
    base-packages: study.dubbo.springboot.service
########## Log配置 ##########
logging:
  config: classpath:logback.xml

