#
dubbo:
  application:
    name: ${spring.application.name}
  #（★）注册中心
  registry:
    address: zookeeper://116.196.74.61:2181
    timeout: 5000
    check: false
  #（★）通信协议
  protocols:
    dubbo:
      name: dubbo
      port: 20880
    rest:
      name: rest
      port: 8081
      server: tomcat
      extension: study.dubbo.springboot.support.rest.RestContainerFilter,
                 study.dubbo.springboot.support.rest.RestWriterInterceptor,
                 study.dubbo.springboot.support.rest.RestExceptionMapper
  #（★）
  provider:
    timeout: 5000
    retries: 0
    dispatcher: message
    version: 1.0.0
  #（★）
  scan:
    base-packages: study.dubbo.springboot.service
